version: 2.5.1.0-extended.{build}

branches:
    only:
        - extended

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "2.5.1.{build}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

build:
    project: ElectronicObserver.sln

before_build:
    - git.exe submodule update --init -- "DockPanelSuite"
    - nuget restore
    - ps: (Get-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8).replace("<BUILD_VERSION>", "$env:APPVEYOR_BUILD_VERSION") | Set-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8

artifacts:
    - path: output
      name: 74eoe-$(APPVEYOR_BUILD_VERSION)
