version: 2.5.4.0-extended.{build}

branches:
    only:
        - extended

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "2.5.4.{build}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

before_build:
    - ps: (Get-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8).replace("<BUILD_VERSION>", "$env:APPVEYOR_BUILD_VERSION") | Set-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8
    - mkdir output-template
    - mkdir output-template\Licenses
    - copy Licenses\*.* output-template\Licenses\
    - copy LICENSE output-template\LICENSE
    - mkdir output-template\Plugins
    - copy NUL output-template\Plugins\plugin_dir

build_script:
    - xcopy /S /E output-template output\
    - git submodule update --init --recursive
    - nuget restore
    - msbuild ElectronicObserver.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - move output output-net45
    - git checkout extended-net40
    - xcopy /S /E output-template output\
    - git submodule update --init --recursive
    - nuget restore
    - msbuild ElectronicObserver.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - move output output-net40
    - ps: if (!((git branch --contains $env:APPVEYOR_REPO_COMMIT) -like '*extended-net40')) { exit -1 }

artifacts:
    - path: output-net45
      name: 74eoe-$(APPVEYOR_BUILD_VERSION)
    - path: output-net40
      name: 74eoe-net40-$(APPVEYOR_BUILD_VERSION)
